import React from "react";
import { Alert, Share } from "react-native";
import { IconButton, useTheme } from "react-native-paper";

interface ShareButtonProps {
    data: Array<{
        key: string;
        label: string;
        accessor: (scenario: any) => string;
    }>;
    scenarios: any[];
    iconSize?: number;
}

export default function ShareButton({
    data,
    scenarios,
    iconSize = 24,
}: ShareButtonProps) {
    const theme = useTheme();

    const handleShare = async () => {
        if (scenarios.length === 0) {
            Alert.alert(
                "No Data",
                "Please select scenarios to compare before sharing.",
            );
            return;
        }

        try {
            // Build the comparison text
            let shareText = "📊 Property Comparison Report\n\n";

            // Add scenario names as header
            shareText += "Scenarios:\n";
            scenarios.forEach((scenario, idx) => {
                shareText += `${idx + 1}. ${scenario.name}\n`;
            });
            shareText += "\n";

            // Add comparison data
            data.forEach((row) => {
                shareText += `${row.label}:\n`;
                scenarios.forEach((scenario, idx) => {
                    const value = row.accessor(scenario);
                    shareText += `  ${idx + 1}. ${value}\n`;
                });
                shareText += "\n";
            });

            shareText += `\nGenerated by HomeLens - ${new Date().toLocaleDateString()}`;

            await Share.share({
                message: shareText,
                title: "Property Comparison",
            });
        } catch (error) {
            console.error("Error sharing:", error);
        }
    };

    return (
        <IconButton
            icon="share-variant"
            size={iconSize}
            onPress={handleShare}
            iconColor={theme.colors.onSurface}
        />
    );
}
